apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-state-metrics-deployment
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-state-metrics
        version: "KUBE_STATE_METRICS_VERSION"
    spec:
      serviceAccountName: default
      containers:
      - name: kube-state-metrics
        image: gcr.io/google_containers/kube-state-metrics:KUBE_STATE_METRICS_VERSION
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
